const { test } = require('node:test');
const assert = require('node:assert/strict');
const { existsSync, readFileSync } = require('node:fs');
const { resolve } = require('node:path');
const vm = require('node:vm');
const root = resolve(__dirname, '../../public');
const js = readFileSync(resolve(root, 'workflow.js'), 'utf8');
const html = readFileSync(resolve(root, 'workflow.html'), 'utf8');
const css = readFileSync(resolve(root, 'workflow.css'), 'utf8');
const app = readFileSync(resolve(root, 'index.html'), 'utf8');
const context = vm.createContext({ URL, atob, Date });
vm.runInContext(js, context);
const invoke = (name, ...args) => { context.args = args; return vm.runInContext(`${name}(...args)`, context); };

test('links: quatro plataformas oficiais, HTTPS e limite de 25', () => {
  for (const url of ['https://www.youtube.com/watch?v=x', 'https://youtu.be/x', 'https://www.tiktok.com/@x/video/1', 'https://instagram.com/reel/x', 'https://m.facebook.com/x']) assert.equal(invoke('officialURL', url), url);
  for (const url of ['https://youtube.com.evil.test/x', 'http://youtube.com/x', 'https://youtube.com:444/x', 'https://user:pass@youtube.com/x', 'https://127.0.0.1/x', 'javascript:alert(1)', 'https://notyoutube.com/x']) assert.throws(() => invoke('officialURL', url));
  assert.equal(invoke('parseLinks', Array(25).fill('https://youtu.be/x').join('\n')).length, 25);
  assert.throws(() => invoke('parseLinks', Array(26).fill('https://youtu.be/x').join('\n')));
});
test('config aceita somente chave pública, rejeita serviço e payload inválido', () => {
  const config = key => ({ supabaseUrl: 'https://project.supabase.co', supabasePublishableKey: key });
  const jwt = role => 'e30.' + Buffer.from(JSON.stringify({ role })).toString('base64url') + '.signature';
  assert.equal(invoke('publicConfig', config(jwt('anon'))).key, jwt('anon'));
  assert.equal(invoke('publicConfig', config('sb_publishable_example')).key, 'sb_publishable_example');
  for (const key of [jwt('service_role'), 'sb_secret_example', 'garbage', null, jwt('authenticated')]) assert.throws(() => invoke('publicConfig', config(key)));
  assert.throws(() => invoke('publicConfig', { ...config(jwt('anon')), supabaseUrl: 'http://localhost' }));
});
test('Lens recusa destino externo, credenciais e link expirado', () => {
  const future = new Date(Date.now() + 60000).toISOString();
  assert.equal(invoke('lensURL', 'https://lens.google.com/uploadbyurl?url=x', future), 'https://lens.google.com/uploadbyurl?url=x');
  for (const url of ['javascript:alert(1)', 'https://lens.google.com.evil.test/', 'https://user@lens.google.com/', 'http://lens.google.com/']) assert.throws(() => invoke('lensURL', url, future));
  assert.throws(() => invoke('lensURL', 'https://lens.google.com/', '2000-01-01'));
  assert.throws(() => invoke('lensURL', 'https://lens.google.com/', 'invalid'));
});
test('DOM: dados externos não viram HTML e não há JavaScript inline', () => {
  assert.doesNotMatch(js, /innerHTML|outerHTML|insertAdjacentHTML|document\.write|\beval\s*\(/);
  assert.doesNotMatch(html, /\son\w+\s*=|javascript:|<script(?![^>]*\bsrc=)/i);
  assert.match(js, /\.textContent =/);
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
  assert.equal(ids.length, new Set(ids).size);
  for (const match of js.matchAll(/\$\('([^']+)'\)/g)) assert.ok(ids.includes(match[1]), 'ID presente: ' + match[1]);
});
test('Supabase fixado na mesma major usada pelo site; sessão padrão e autenticação bearer', () => {
  assert.match(app, /@supabase\/supabase-js@2(?:\/|\.)/);
  assert.match(js, /@supabase\/supabase-js@2\.116\.0\/\+esm/);
  assert.match(js, /createClient\(config\.url, config\.key\)/);
  assert.match(js, /headers\.Authorization = 'Bearer '/);
  assert.match(js, /api\('\/api\/config', \{\}, true\)/);
  assert.match(js, /redirect: 'error'/);
  assert.doesNotMatch(js, /localStorage\.setItem|console\.log/);
});
test('downloads do app principal enviam a sessão explicitamente', () => {
  assert.match(app, /function authenticatedApiFetch\(input, init\)/);
  assert.match(app, /headers\.set\('Authorization','Bearer '\+session\.access_token\)/);
  assert.match(app, /var response=await authenticatedApiFetch\(dlUrl\)/);
  assert.match(app, /var res = await authenticatedApiFetch\('\/api\/video-dl\?' \+ qs\)/);
});
test('consentimentos, escolhas e API de execução independentes', () => {
  assert.doesNotMatch(html, /\bchecked\b/);
  assert.match(js, /request_id: uuid\(\)/);
  assert.match(js, /pendingRun\(attempts, runKey\(\), endpoint, body, \(\) => crypto\.randomUUID\(\)\)/);
  assert.match(js, /allow_paid: \$\('allow-paid'\)\.checked/);
  assert.match(js, /allow_frame_upload: \$\('allow-frame-upload'\)\.checked/);
  assert.match(js, /if \(!individual\) body\.steps = steps/);
  assert.match(js, /run\(\[name\], true\)/);
  assert.match(js, /lens\.addEventListener\('click'/);
  assert.match(js, /URL\.createObjectURL\(blob\)/);
  assert.match(js, /URL\.revokeObjectURL\(href\)/);
});
test('polling com intervalo, cancelamento e somente em estados ativos', () => {
  assert.match(js, /new AbortController\(\)/);
  assert.match(js, /visibilitychange/);
  assert.match(js, /document\.hidden\) cancel\(\)/);
  assert.match(js, /generation !== state\.generation/);
  assert.match(js, /\['queued', 'running'\]\.includes\(stage\.status\)/);
  assert.match(js, /4000\)/);
  assert.doesNotMatch(js, /setInterval/);
});
test('PATCH parcial e edição preservada durante resposta e polling', () => {
  assert.match(js, /if \(!state\.dirty\.has\(field\)\)/);
  assert.match(js, /creating \|\| state\.dirty\.has\(field\)/);
  assert.match(js, /\$\(field\)\.value === value\) state\.dirty\.delete\(field\)/);
  assert.match(js, /creating \? 'POST' : 'PATCH'/);
  assert.match(js, /state\.dirty\.size/);
  for (const status of ['pending', 'queued', 'running', 'ready', 'failed', 'waiting_input', 'unknown', 'stale']) assert.ok(vm.runInContext(`Object.hasOwn(STATUS, '${status}')`, context));
  assert.match(html, /hash/);
  assert.match(html, /Nenhuma etapa é refeita automaticamente/);
});
test('acessibilidade e responsividade', () => {
  assert.match(html, /lang="pt-BR"/);
  assert.match(html, /aria-live="polite"/);
  assert.match(html, /href="#workspace"/);
  assert.match(html, /href="\.\/workflow\.css"/);
  assert.match(html, /src="\.\/workflow\.js\?v=/);
  assert.match(html, /class="workflow-rail"/);
  assert.match(html, /workflow\.js\?v=20260910-workflow-controls-21/);
  assert.doesNotMatch(html, /download-local-note[^>]*>Ação manual/);
  assert.match(html, /<fieldset id="app">/);
  assert.doesNotMatch(html, /<fieldset id="app" disabled>/);
  assert.match(html, /id="save"[^>]*type="submit"/);
  assert.match(html, /Salve antes de executar etapas ou importar arquivos/);
  assert.doesNotMatch(html, /id="dirty"/);
  assert.doesNotMatch(html, /Abra uma função por vez\. O link-base é o ponto de partida para todo o workflow\./);
  assert.match(html, /id="new-project-dialog"/);
  assert.match(html, /id="new-project-name"[^>]*required/);
  assert.match(html, /id="new-project-channel"[^>]*required/);
  assert.match(js, /newProjectDialog\.showModal\(\)/);
  assert.match(js, /\$\('notice'\)\.hidden = true/);
  assert.match(html, /class="workflow-topbar"/);
  assert.match(html, /class="workflow-product"[^>]*>[\s\S]*<small>V2\.0<\/small>/);
  assert.doesNotMatch(html, /<small>V1\.0<\/small>/);
  assert.doesNotMatch(html, /class="back-link"/);
  assert.match(html, /class="account-pill" href="\/app\?open=account"/);
  assert.match(app, /accountRequested = new URLSearchParams\(window\.location\.search\)\.get\('open'\) === 'account'/);
  assert.match(app, /setUserMenu\(true\)/);
  assert.equal((html.match(/class="workflow-nav-item"/g) || []).length, 7);
  assert.match(html, /href="#editor-heading"[^>]*>.*<span>Logs<\/span>/s);
  const navLabels = [...html.matchAll(/class="workflow-nav-item"[^>]*>[\s\S]*?<span>([^<]+)<\/span><\/a>/g)].map(match => match[1]);
  assert.deepEqual(navLabels, ['Buscar', 'Editorial', 'Voz', 'Downloads', 'Etapas', 'Thumbnail', 'Logs']);
  assert.match(html, /id="editor-heading">Projeto e entradas<\/h2>/);
  assert.match(html, /Referências de pesquisa/);
  assert.match(html, /Para baixar mídias, use a lista própria em Downloads/);
  assert.match(html, /Transcrição original/);
  assert.match(html, /Roteiro salvo/);
  assert.match(html, /Título salvo/);
  assert.match(html, /href="#editorial-heading"[^>]*>.*<span>Editorial<\/span>/s);
  assert.match(html, /id="editorial-run-roteiro"/);
  assert.match(html, /id="editorial-run-titulos"/);
  assert.match(html, /id="editorial-run-seo"/);
  assert.match(js, /run\(\[name\], true\)/);
  assert.match(js, /function executeStage/);
  assert.match(js, /const unavailable = !localPreview && capability\?\.available !== true/);
  assert.match(js, /\|\| unavailable/);
  assert.match(js, /const EDITORIAL_REQUIREMENTS/);
  assert.match(js, /function editorialInputError/);
  assert.match(js, /function capabilityLabel/);
  assert.match(js, /requer autorização/);
  assert.match(js, /const canAssess = localPreview \|\| state\.capabilities\.length > 0/);
  assert.match(js, /option\.dataset\.status/);
  assert.match(js, /Crie ou selecione um projeto e salve-o antes de executar esta função/);
  assert.match(js, /A etapa \$\{STAGES\[unavailable\]/);
  assert.match(js, /viewHashes = .*editorial/);
  assert.match(html, /href="#import-heading"[^>]*>.*<span>Voz<\/span>/s);
  assert.doesNotMatch(html, /href="#import-heading"[^>]*>.*<span>Mídia<\/span>/s);
  assert.match(html, /href="#downloads-heading"[^>]*>.*<span>Downloads<\/span>/s);
  assert.match(html, /href="#flow-heading"[^>]*>.*<span>Etapas<\/span>/s);
  assert.match(html, /id="flow-heading">Acompanhe a execução<\/h2>/);
  assert.match(html, /Esta tela é somente de acompanhamento/);
  assert.match(css, /scroll-snap-type:x proximity/);
  assert.match(html, /href="#artifacts-heading"[^>]*>.*<span>Thumbnail<\/span>/s);
  assert.doesNotMatch(html, /href="#artifacts-heading"[^>]*>.*<span>Resultados<\/span>/s);
  assert.match(html, /class="project-queue"/);
  assert.match(html, /id="start-stage-options"/);
  assert.match(html, /class="consents start-consents"[\s\S]*id="allow-paid"/);
  assert.doesNotMatch(html, /id="run"/);
  assert.doesNotMatch(html, /Executar etapas selecionadas/);
  assert.match(html, /Nenhuma etapa é iniciada nesta tela/);
  assert.match(js, /className = 'job-delete'/);
  assert.match(js, /method: 'DELETE'/);
  assert.match(js, /function prepareAnalysis/);
  assert.match(js, /const hasBaseUrl = Boolean\(\$\('base_url'\)\.value\.trim\(\)\)/);
  assert.match(js, /const masterBlocked =/);
  assert.match(js, /Cole um link oficial de YouTube/);
  assert.match(css, /job-delete/);
  assert.match(js, /window\.location\.protocol === 'file:'/);
  assert.match(js, /\$\('notice'\)\.hidden = true/);
  assert.match(js, /const localPreview = window\.location\.protocol === 'file:'/);
  assert.match(js, /Ver etapas selecionadas/);
  assert.match(js, /window\.location\.reload\(\)/);
  assert.match(js, /function renderStartStageOptions/);
  assert.match(js, /function renderDownloadCandidates/);
  assert.match(js, /function downloadVideo/);
  assert.match(js, /const blocked = state\.busy \|\| unresolved \|\| preserved/);
  assert.match(js, /Selecione ou crie um projeto e salve-o antes de importar/);
  assert.match(html, /Você pode escolher o arquivo primeiro/);
  assert.match(js, /api\('\/api\/video-dl\?' \+ query/);
  assert.match(html, /id="download-consent" type="checkbox"/);
  assert.match(html, /id="download-all"[^>]*>Baixar vídeos/);
  assert.match(html, /id="download-links"/);
  assert.match(html, /option value="4320">8K \(4320p\)/);
  assert.match(html, /option value="2160">4K \(2160p\)/);
  assert.match(html, /option value="1440">2K \/ QHD \(1440p\)/);
  assert.match(html, /option value="720">720p HD/);
  assert.match(html, /maior resolução disponível até o limite escolhido/);
  assert.match(js, /download-all.*addEventListener\('click'/s);
  assert.match(js, /downloadAll\.disabled = !enabled/);
  assert.match(js, /const hasValidEntries = downloadEntries\(\)\.some\(entry => !entry\.error\)/);
  assert.match(js, /const enabled = Boolean\(consent\?\.checked\) && canRequest && hasValidEntries/);
  assert.match(js, /Marque a confirmação de autorização antes de baixar/);
  assert.match(js, /Cole pelo menos um link oficial válido para começar/);
  assert.match(html, /id="thumbnail-tool-line"/);
  assert.match(js, /function resizeHandle/);
  assert.match(js, /type: resizing \? 'resize' : 'move'/);
  assert.match(js, /Arraste qualquer alça/);
  assert.match(js, /layer\.width = Math\.max\(20/);
  assert.match(js, /layer\.height = Math\.max\(20/);
  assert.match(js, /const handles = \{ nw:/);
  assert.match(js, /ns-resize/);
  assert.match(html, /id="thumbnail-context-menu"/);
  assert.match(html, /id="thumbnail-page-menu"/);
  assert.match(html, /id="thumbnail-add-page"/);
  assert.match(html, /data-page-action="guide-horizontal"/);
  assert.match(html, /data-thumbnail-action="component-layer"/);
  assert.match(html, /data-thumbnail-action="download-layer"/);
  assert.match(html, /data-page-action="copy-style"/);
  assert.match(js, /Object\.defineProperty\(editor, 'layers'/);
  assert.match(js, /function objectAction/);
  assert.match(js, /function pageAction/);
  assert.match(js, /function renderPages/);
  assert.match(js, /thumbnail-copy-layer/);
  assert.match(js, /function selectField/);
  assert.match(js, /selectField\('Fonte'/);
  assert.match(js, /Bebas Neue/);
  assert.match(css, /:focus-visible/);
  assert.match(css, /BebasNeue-Regular\.ttf/);
  assert.ok(existsSync(resolve(root, 'fonts/BebasNeue-Regular.ttf')));
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /max-width:540px/);
  assert.match(css, /\.section-intro/);
  assert.match(css, /overscroll-behavior-inline/);
  assert.match(css, /button,input,textarea,select\{max-width:100%\}/);
});
test('limites HTML e validação de textos programáticos seguem a API', () => {
  for (const [field, limit] of Object.entries({ name: 120, channel: 80, title: 180, transcript: 20000, script: 20000 })) {
    assert.match(html, new RegExp(`id="${field}"[^>]*maxlength="${limit}"`));
    assert.doesNotThrow(() => invoke('validateFields', { [field]: 'x'.repeat(limit) }));
    assert.throws(() => invoke('validateFields', { [field]: 'x'.repeat(limit + 1) }));
  }
  assert.match(js, /validateFields\(body\)/);
});
test('saída editorial aninhada e legada, sem sobrescrever edições', () => {
  assert.equal(invoke('editorialText', { data: { script: 'Roteiro gerado' } }, 'script'), 'Roteiro gerado');
  assert.equal(invoke('editorialText', { data: { title: 'Título gerado' } }, 'title'), 'Título gerado');
  assert.equal(invoke('editorialText', { script: 'Legado' }, 'script'), 'Legado');
  assert.equal(invoke('editorialText', 'Texto direto', 'script'), 'Texto direto');
  assert.equal(invoke('editorialText', { data: { title: ['não é texto'] } }, 'title'), null);
  assert.match(js, /const output = stage\?\.output\?\.data \?\? stage\?\.output/);
  assert.match(js, /!state\.dirty\.has\(field\) && !\$\(field\)\.value\.trim\(\) && value\?\.trim\(\)/);
  assert.match(js, /state\.dirty\.has\(field\) \|\| \$\(field\)\.value\.trim\(\)/);
});
test('erros da API e aviso 202 persistem como texto; motivo disponível também aparece', () => {
  assert.match(invoke('apiErrorMessage', { error: 'O título excede 180 caracteres.' }, 400), /O título excede 180 caracteres/);
  assert.match(invoke('apiErrorMessage', { error: { message: 'Etapa bloqueada.' } }, 403), /Etapa bloqueada/);
  assert.match(invoke('apiErrorMessage', null, 502), /HTTP 502/);
  assert.match(invoke('apiErrorMessage', {}, 401), /Entre novamente/);
  assert.match(js, /capability\?\.reason \|\| \(capability\?\.available === true/);
  assert.match(js, /capability\?\.available === true/);
  assert.match(js, /warnings\.set\(key, warning\)/);
  assert.match(js, /\$\('run-warning'\)\.textContent = warnings\.get\(runKey\(\)\)/);
  assert.match(html, /id="run-warning" role="status" aria-live="polite"/);
});
test('tentativa incerta preserva ID, endpoint, etapas e consentimentos até resposta', () => {
  const attempts = new Map(); let generated = 0;
  const uuid = () => 'id-' + ++generated;
  const initial = invoke('pendingRun', attempts, 'user/job-a', '/jobs/a/run', { steps: ['voz'], allow_paid: true, allow_frame_upload: false }, uuid);
  const retry = invoke('pendingRun', attempts, 'user/job-a', '/jobs/a/stages/frames/run', { steps: ['frames'], allow_paid: false }, uuid);
  assert.equal(retry, initial);
  assert.equal(retry.body.request_id, 'id-1');
  assert.equal(retry.endpoint, '/jobs/a/run');
  assert.equal(retry.body.allow_paid, true);
  assert.deepEqual(retry.body.steps, ['voz']);
  assert.equal(generated, 1);
  assert.notEqual(invoke('pendingRun', attempts, 'user/job-b', '/jobs/b/run', {}, uuid).body.request_id, initial.body.request_id);
  attempts.delete('user/job-a');
  assert.notEqual(invoke('pendingRun', attempts, 'user/job-a', '/jobs/a/run', {}, uuid).body.request_id, initial.body.request_id);
  assert.match(js, /api\(attempt\.endpoint, \{ method: 'POST', body: JSON\.stringify\(attempt\.body\) \}\)/);
  assert.match(js, /\$\('retry-run'\)\.addEventListener\('click'/);
  assert.match(js, /!\[408, 429\]\.includes\(error\.status\)/);
  assert.match(js, /state\.busy \|\| unresolved/);
});
test('importação limita tamanho e MIME sem ler ou enviar arquivos reais', () => {
  const file = (type, size = 1024) => ({ name: 'selecionado', type, size });
  assert.equal(invoke('importMime', 'base', file('video/mp4', 50 * 1024 * 1024)), 'video/mp4');
  assert.equal(invoke('importMime', 'voice', file('audio/mpeg')), 'audio/mpeg');
  assert.equal(invoke('importMime', 'voice', file('audio/wav')), 'audio/wav');
  assert.equal(invoke('importMime', 'voice', file('audio/x-wav')), 'audio/wav');
  for (const size of [0, -1, NaN, Infinity, 50 * 1024 * 1024 + 1]) assert.throws(() => invoke('importMime', 'base', file('video/mp4', size)));
  for (const type of ['audio/mpeg', 'video/webm', 'application/octet-stream', 'text/html', '']) assert.throws(() => invoke('importMime', 'base', file(type)));
  assert.throws(() => invoke('importMime', 'voice', file('video/mp4')));
  assert.throws(() => invoke('importMime', 'base', null));
  assert.throws(() => invoke('importMime', 'other', file('video/mp4')));
});
test('importação usa seleção individual, botão explícito e corpo binário autenticado', () => {
  const inputs = [...html.matchAll(/<input[^>]*type="file"[^>]*>/g)].map(match => match[0]);
  assert.equal(inputs.length, 3);
  for (const input of inputs) assert.doesNotMatch(input, /\bmultiple\b|\bdirectory\b/);
  assert.match(html, /id="import-base-file"[^>]*accept="video\/mp4,\.mp4"/);
  assert.match(html, /id="import-voice-file"[^>]*accept="audio\/mpeg,audio\/wav,\.mp3,\.wav"/);
  assert.match(html, /id="thumbnail-image"[^>]*accept="image\/png,image\/jpeg,image\/webp"/);
  assert.match(html, /id="thumbnail-canvas"[^>]*width="1080"[^>]*height="1920"/);
  assert.match(html, /id="thumbnail-add-text"/);
  assert.match(html, /id="thumbnail-add-shape"/);
  assert.match(html, /id="thumbnail-export"/);
  assert.match(html, /id="thumbnail-export-jpeg"/);
  assert.match(html, /id="thumbnail-layers"/);
  assert.match(html, /Local · nada é enviado automaticamente/);
  assert.match(js, /Nada foi enviado ao servidor/);
  assert.match(js, /canvas\.toBlob/);
  assert.match(js, /image\/jpeg/);
  assert.match(js, /const extension = format === 'image\/jpeg' \? 'jpg' : 'png'/);
  assert.match(html, /Apenas o arquivo escolhido será enviado ao armazenamento privado deste projeto/);
  assert.match(js, /\.addEventListener\('change', controls\)/);
  assert.match(js, /\.addEventListener\('click', \(\) => action\(\(\) => importMedia\(kind\)\)\)/);
  assert.match(js, /const file = input\.files\?\.\[0\]/);
  assert.match(js, /api\(path\(\) \+ '\/import\?kind=' \+ kind, \{ method: 'POST', body: file, rawMime, timeoutMs: 130000 \}\)/);
  assert.match(js, /headers\['Content-Type'\] = rawMime \|\| 'application\/json'/);
  assert.match(js, /timeoutMs = 30000/);
  assert.match(js, /setTimeout\(\(\) => controller\.abort\(\), timeoutMs\)/);
  assert.match(js, /headers\.Authorization = 'Bearer '/);
  assert.doesNotMatch(js, /FileReader|readAsDataURL|showDirectoryPicker|new FormData/);
});
test('importação exige projeto salvo, preserva mídia e só aplica estados da API', () => {
  const source = js.slice(js.indexOf('async function importMedia(kind)'), js.indexOf('async function run(steps'));
  assert.match(source, /if \(!state\.job \|\| state\.dirty\.size\) throw/);
  assert.match(source, /if \(attempts\.has\(runKey\(\)\)\) throw/);
  assert.match(source, /kind === 'base' && importedBases\.has\(runKey\(\)\)/);
  assert.match(source, /stage\.name === 'voz' && stage\.status === 'ready'/);
  assert.match(source, /error\.status === 409/);
  assert.match(source, /fill\(data\.job\); renderStages\(data\.stages\); renderArtifacts\(data\.artifacts\)/);
  assert.doesNotMatch(source, /\brun\(|status\s*=\s*'ready'|JSON\.stringify\(file\)/);
  assert.match(js, /cancel\(\); resetImports\(\); state\.job = job/);
});
